content:
  - name: posts
    label: Posts
    path: src/content/til
    type: collection
    filename: '{hour}-{minute}-{second}.md'
    view:
      fields: [title, date, tags, published]
      primary: title
    fields:
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - {name: tags, label: Tags, type: string, list: true}
      - {name: published, label: Published, type: boolean}
      - {name: body, label: Body, type: code, options: { language: markdown }}
