content:
  - name: posts
    label: Posts
    path: src/content/til
    type: collection
    filename: "{hour}-{minute}-{second}-{primary}.md"
    view:
      fields: [ title, date, tags, published ]
      primary: title
      sort: [ title ]
      default: { sort: title, order: desc }
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: published, label: Published, type: boolean}
      - { name: body, label: Body, type: rich-text }