content:
  - name: posts
    label: Posts
    path: src/content/til
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: string }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: published, label: Published, type: boolean}